import Head from "next/head";
import { useState } from "react";
import {
  BillControl,
  Brands,
  Business,
  CallToAction,
  CardDeal,
  Counter,
  Footer,
  Header,
  Hero,
} from "../components";
import Opinions from "../components/Opinions";
import SideBar from "../components/subComps/SideBar";

export default function Home() {
  const [isSideBarOpen, setIsSideBarOpen] = useState(false);
  return (
    <main className="bg-custom-darkBackground ">
      <Head>
        <title>Hoo Bank Demo</title>
        <meta
          name="description"
          content="GDemo page generated by Reza Sadeghzadeh"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        setIsSideBarOpen={setIsSideBarOpen}
        isSideBarOpen={isSideBarOpen}
      />
      <SideBar
        setIsSideBarOpen={setIsSideBarOpen}
        isSideBarOpen={isSideBarOpen}
      />
      <Hero />
      <Counter />
      <Business />
      <BillControl />
      <CardDeal />
      <Opinions />
      <Brands />
      <CallToAction />
      <Footer />
    </main>
  );
}
