import Head from "next/head";
import Business from "../components/Business";
import Header from "../components/Header";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <main className="bg-custom-darkBackground ">
      <Head>
        <title>Hoo Bank Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      {/* <Business /> */}
    </main>
  );
}
